apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: predict
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
      - name: predict
        image: tensorflow/serving:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret_key
        - name: S3_ENDPOINT
          value: "minio-service:9000"
        - name: S3_USE_HTTPS
          value: "0"
        - name: MODEL_NAME
          value: small_computers0
        - name: MODEL_BASE_PATH
          value: "s3://bucket0011/trained_models"
        ports:
        - containerPort: 8500
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: predict-service
spec:
  #type: LoadBalancer
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
      name: grpc
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: predict
