apiVersion: v1
kind: Service
metadata:
  name: pipeline-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: pipeline-api
---
apiVersion: v1
kind: Service
metadata:
  name: capture-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: capture