apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train
        image: flexiblevision/train
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access_key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret_key
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: apiUrl
